/**
 * ProcureFlow Comprehensive Agricultural Crop Catalogue
 * Covers all major Indian MSP and mandi procurement categories:
 * - Cereals & Grains
 * - Pulses
 * - Oilseeds
 * - Commercial & Fibre
 * - Vegetables
 * - Fruits
 *
 * Uses authentic, reliable public agricultural photography (Unsplash).
 * Structured data allows easy extension with additional crops.
 */

export type CropCategory =
  | "Cereals"
  | "Pulses"
  | "Oilseeds"
  | "Commercial"
  | "Vegetables"
  | "Fruits";

export interface CropItem {
  id: string;
  cropName: string;
  commonName: string;
  variety: string;
  category: CropCategory;
  imageUrl: string;
  mspPerQuintal: number;
  govtBonusPerQuintal: number;
  effectiveRatePerQuintal: number;
  maxMoisturePercent: number;
  season: string;
  unit: string;
  description: string;
}

export const CROP_CATALOGUE: CropItem[] = [
  // ==========================================
  // 1. CEREALS & GRAINS
  // ==========================================
  {
    id: "paddy-common",
    cropName: "Paddy (Common / Rice)",
    commonName: "Paddy / Rice (Dhan)",
    variety: "Standard / MTU 1010 / IR 64",
    category: "Cereals",
    imageUrl: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 2300,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 2300,
    maxMoisturePercent: 17.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Standard grade paddy for central pool procurement and public distribution.",
  },
  {
    id: "paddy-grade-a",
    cropName: "Paddy (Grade A)",
    commonName: "Fine Paddy (BPT 5204 / Sona Masuri)",
    variety: "Grade A / BPT 5204",
    category: "Cereals",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 2320,
    govtBonusPerQuintal: 50,
    effectiveRatePerQuintal: 2370,
    maxMoisturePercent: 17.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Premium slender-grain paddy eligible for state government procurement incentive bonus.",
  },
  {
    id: "wheat",
    cropName: "Wheat (Gehun)",
    commonName: "Wheat",
    variety: "Kalyan Sona / Sharbati / HD 2967",
    category: "Cereals",
    imageUrl: "https://images.unsplash.com/photo-1501430654243-c934cec2e1c0?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 2275,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 2275,
    maxMoisturePercent: 12.0,
    season: "Rabi 2025-26",
    unit: "quintal",
    description: "Prime quality milling wheat for buffer stocking and fair price mandi procurement.",
  },
  {
    id: "maize",
    cropName: "Maize (Makka / Corn)",
    commonName: "Maize / Corn",
    variety: "Hybrid Yellow / Ganga 11",
    category: "Cereals",
    imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 2225,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 2225,
    maxMoisturePercent: 14.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Industrial, poultry, and food grade yellow hybrid maize grain.",
  },
  {
    id: "jowar",
    cropName: "Jowar (Sorghum)",
    commonName: "Great Millet / Sorghum",
    variety: "Maldandi / CSH 16 Hybrid",
    category: "Cereals",
    imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 3371,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 3371,
    maxMoisturePercent: 12.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Nutritious white sorghum millet purchased under Shree Anna initiative.",
  },
  {
    id: "bajra",
    cropName: "Bajra (Pearl Millet)",
    commonName: "Pearl Millet / Sajje",
    variety: "Hybrid Pearl / HHB 67",
    category: "Cereals",
    imageUrl: "https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 2625,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 2625,
    maxMoisturePercent: 12.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "High-iron resilient dryland millet procuring at state agricultural yards.",
  },
  {
    id: "ragi",
    cropName: "Ragi (Finger Millet)",
    commonName: "Finger Millet / Nachni",
    variety: "GPU-28 / Indaf-8",
    category: "Cereals",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 4290,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 4290,
    maxMoisturePercent: 12.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Calcium-rich millets procuring under state nutrition and public food programs.",
  },
  {
    id: "barley",
    cropName: "Barley (Jau)",
    commonName: "Barley",
    variety: "RD 2035 / DWRB 123",
    category: "Cereals",
    imageUrl: "https://images.unsplash.com/photo-1437252611977-07f74518abb7?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 1850,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 1850,
    maxMoisturePercent: 12.0,
    season: "Rabi 2025-26",
    unit: "quintal",
    description: "High-grade feed and malt barley grain.",
  },

  // ==========================================
  // 2. PULSES (DAL)
  // ==========================================
  {
    id: "red-gram",
    cropName: "Red Gram (Tur / Toor / Arhar)",
    commonName: "Pigeon Pea / Toor Dal",
    variety: "Maruti / Asha (ICPL 87119)",
    category: "Pulses",
    imageUrl: "https://images.unsplash.com/photo-1585996746979-3079ff176162?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 7550,
    govtBonusPerQuintal: 200,
    effectiveRatePerQuintal: 7750,
    maxMoisturePercent: 12.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Prime pulse crop with special government price stabilization incentive.",
  },
  {
    id: "green-gram",
    cropName: "Green Gram (Moong / Mung)",
    commonName: "Moong Dal / Green Gram",
    variety: "Shin Moong / Samrat / PDM 139",
    category: "Pulses",
    imageUrl: "https://images.unsplash.com/photo-1627485937980-221c88ac04f9?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 8558,
    govtBonusPerQuintal: 200,
    effectiveRatePerQuintal: 8758,
    maxMoisturePercent: 12.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Highest MSP valued short-duration summer/kharif protein pulse.",
  },
  {
    id: "black-gram",
    cropName: "Black Gram (Urad)",
    commonName: "Urad Dal / Black Matpe",
    variety: "PU-19 / VBN-8",
    category: "Pulses",
    imageUrl: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 7400,
    govtBonusPerQuintal: 150,
    effectiveRatePerQuintal: 7550,
    maxMoisturePercent: 12.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Essential South Indian staple pulse for domestic food security stocking.",
  },
  {
    id: "bengal-gram",
    cropName: "Bengal Gram (Chickpea / Chana)",
    commonName: "Desi Chana / Chickpea",
    variety: "Desi / Kabuli / JG 11",
    category: "Pulses",
    imageUrl: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 5440,
    govtBonusPerQuintal: 100,
    effectiveRatePerQuintal: 5540,
    maxMoisturePercent: 12.0,
    season: "Rabi 2025-26",
    unit: "quintal",
    description: "Major rabi legume procuring in AP, Telangana, and Central Indian mandis.",
  },
  {
    id: "lentils",
    cropName: "Lentils (Masoor Dal)",
    commonName: "Masoor / Red Lentil",
    variety: "Small Seeded / DPL 62",
    category: "Pulses",
    imageUrl: "https://images.unsplash.com/photo-1585996746979-3079ff176162?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 6425,
    govtBonusPerQuintal: 100,
    effectiveRatePerQuintal: 6525,
    maxMoisturePercent: 12.0,
    season: "Rabi 2025-26",
    unit: "quintal",
    description: "Nutritious red lentil pulse with guaranteed procurement support.",
  },

  // ==========================================
  // 3. OILSEEDS
  // ==========================================
  {
    id: "groundnut",
    cropName: "Groundnut (In Shell / Peanut)",
    commonName: "Peanut / Groundnut / Palleelu",
    variety: "TMV-2 / Kadiri-6 / TAG-24",
    category: "Oilseeds",
    imageUrl: "https://images.unsplash.com/photo-1567894340315-735d7c361db0?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 6783,
    govtBonusPerQuintal: 150,
    effectiveRatePerQuintal: 6933,
    maxMoisturePercent: 8.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "High oil-content pod groundnut for AP and Gujarat edible oil processing.",
  },
  {
    id: "soybean",
    cropName: "Soybean (Yellow)",
    commonName: "Soybean",
    variety: "JS 335 / NRC 37",
    category: "Oilseeds",
    imageUrl: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 4892,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 4892,
    maxMoisturePercent: 12.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Clean yellow soybean grain for direct procurement at mandi terminals.",
  },
  {
    id: "sunflower",
    cropName: "Sunflower",
    commonName: "Sunflower Seed",
    variety: "KBSH-44 / DRSH-1",
    category: "Oilseeds",
    imageUrl: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 7280,
    govtBonusPerQuintal: 100,
    effectiveRatePerQuintal: 7380,
    maxMoisturePercent: 9.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Premium sunflower seed for high-grade edible vegetable oil extraction.",
  },
  {
    id: "sesame",
    cropName: "Sesame (Til)",
    commonName: "Gingelly / Sesame / Nuvvulu",
    variety: "White Till / RT 351",
    category: "Oilseeds",
    imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 9267,
    govtBonusPerQuintal: 150,
    effectiveRatePerQuintal: 9417,
    maxMoisturePercent: 8.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "High-value export quality white and brown sesame seeds.",
  },
  {
    id: "mustard",
    cropName: "Mustard (Sarson / Rai)",
    commonName: "Mustard / Rapeseed",
    variety: "Pusa Bold / Varuna",
    category: "Oilseeds",
    imageUrl: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 5650,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 5650,
    maxMoisturePercent: 8.0,
    season: "Rabi 2025-26",
    unit: "quintal",
    description: "Crucial winter oilseed crop for North & Central Indian procurement.",
  },

  // ==========================================
  // 4. COMMERCIAL & FIBRE CROPS
  // ==========================================
  {
    id: "cotton-long",
    cropName: "Cotton (Long Staple)",
    commonName: "BT Cotton (Kapas)",
    variety: "BT Cotton / DCH-32 / Bunny",
    category: "Commercial",
    imageUrl: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 7521,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 7521,
    maxMoisturePercent: 8.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "CCI certified long-staple white cotton lint and raw seed kapas.",
  },
  {
    id: "cotton-medium",
    cropName: "Cotton (Medium Staple)",
    commonName: "Medium Staple Cotton",
    variety: "Surabhi / F-1378",
    category: "Commercial",
    imageUrl: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 7121,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 7121,
    maxMoisturePercent: 8.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Standard medium staple raw cotton for textile milling procurement.",
  },
  {
    id: "sugarcane",
    cropName: "Sugarcane",
    commonName: "Sugarcane (Ganna / Cheruku)",
    variety: "Co 86032 / Mandya / Co 0238",
    category: "Commercial",
    imageUrl: "https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 340,
    govtBonusPerQuintal: 15,
    effectiveRatePerQuintal: 355,
    maxMoisturePercent: 10.0,
    season: "Annual 2025-26",
    unit: "quintal",
    description: "Statutory FRP cane with high sucrose recovery percentage for sugar mills.",
  },
  {
    id: "tobacco",
    cropName: "Tobacco (FCV)",
    commonName: "Flue Cured Virginia Tobacco",
    variety: "Siri / Kanchan / Hema",
    category: "Commercial",
    imageUrl: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 11500,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 11500,
    maxMoisturePercent: 10.0,
    season: "Annual 2025-26",
    unit: "quintal",
    description: "Tobacco Board AP auction platform graded Virginia cured leaf.",
  },
  {
    id: "jute",
    cropName: "Jute (Raw Fibre)",
    commonName: "Golden Fibre Jute (Patson)",
    variety: "TD-5 / JRO 524",
    category: "Commercial",
    imageUrl: "https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 5050,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 5050,
    maxMoisturePercent: 15.0,
    season: "Kharif 2025-26",
    unit: "quintal",
    description: "Jute Corporation of India certified baled and raw golden fibre.",
  },

  // ==========================================
  // 5. VEGETABLES (HORTICULTURE)
  // ==========================================
  {
    id: "tomato",
    cropName: "Tomato",
    commonName: "Tomato (Tamatar)",
    variety: "Hybrid Roma / Vaishnavi / PKM-1",
    category: "Vegetables",
    imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 1850,
    govtBonusPerQuintal: 100,
    effectiveRatePerQuintal: 1950,
    maxMoisturePercent: 20.0,
    season: "All-Season 2025-26",
    unit: "quintal",
    description: "Farm-fresh firm round red tomatoes for Mandi APMC vegetable yards.",
  },
  {
    id: "potato",
    cropName: "Potato",
    commonName: "Potato (Aloo)",
    variety: "Kufri Jyoti / Kufri Pukhraj",
    category: "Vegetables",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 1450,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 1450,
    maxMoisturePercent: 18.0,
    season: "Rabi 2025-26",
    unit: "quintal",
    description: "Cold-store and fresh harvest graded table potatoes.",
  },
  {
    id: "onion",
    cropName: "Onion",
    commonName: "Red Onion (Pyaz / Ulli)",
    variety: "Nasik Red / Agrifound Dark Red",
    category: "Vegetables",
    imageUrl: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 2100,
    govtBonusPerQuintal: 150,
    effectiveRatePerQuintal: 2250,
    maxMoisturePercent: 15.0,
    season: "Kharif & Late Kharif",
    unit: "quintal",
    description: "Export and mandi auction grade cured red onions.",
  },
  {
    id: "brinjal",
    cropName: "Brinjal (Eggplant / Vankaya)",
    commonName: "Brinjal / Aubergine",
    variety: "Pusa Purple Long / Guntur Round",
    category: "Vegetables",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 1600,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 1600,
    maxMoisturePercent: 22.0,
    season: "All-Season 2025-26",
    unit: "quintal",
    description: "Shiny, fresh purple and green harvested vegetable eggplants.",
  },
  {
    id: "cabbage",
    cropName: "Cabbage",
    commonName: "Green Cabbage (Patta Gobhi)",
    variety: "Golden Acre / Pride of India",
    category: "Vegetables",
    imageUrl: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 1200,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 1200,
    maxMoisturePercent: 20.0,
    season: "Winter 2025-26",
    unit: "quintal",
    description: "Tight-headed crisp green fresh cabbage for vegetable collection hubs.",
  },
  {
    id: "cauliflower",
    cropName: "Cauliflower",
    commonName: "Cauliflower (Phool Gobhi)",
    variety: "Pusa Snowball / Madhuri",
    category: "Vegetables",
    imageUrl: "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 1550,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 1550,
    maxMoisturePercent: 20.0,
    season: "Winter 2025-26",
    unit: "quintal",
    description: "Pure white compact curds with green leaves intact.",
  },
  {
    id: "carrot",
    cropName: "Carrot",
    commonName: "Carrot (Gajar)",
    variety: "Pusa Kesar / Kuroda",
    category: "Vegetables",
    imageUrl: "https://images.unsplash.com/photo-1598170845058-32b9d6a5c317?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 1900,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 1900,
    maxMoisturePercent: 18.0,
    season: "Rabi 2025-26",
    unit: "quintal",
    description: "Crisp, sweet orange-red field harvested root carrots.",
  },
  {
    id: "chilli",
    cropName: "Green Chilli & Dry Red Chilli",
    commonName: "Chilli (Mirchi)",
    variety: "Guntur Sannam / Byadagi / Teja",
    category: "Vegetables",
    imageUrl: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 14200,
    govtBonusPerQuintal: 300,
    effectiveRatePerQuintal: 14500,
    maxMoisturePercent: 10.0,
    season: "Annual 2025-26",
    unit: "quintal",
    description: "Famous Guntur AP spice yard auction grade pungent chillies.",
  },
  {
    id: "okra",
    cropName: "Okra (Bhindi / Ladyfinger)",
    commonName: "Ladyfinger / Bhendi / Bendakaya",
    variety: "Pusa Sawani / Arka Anamika",
    category: "Vegetables",
    imageUrl: "https://images.unsplash.com/photo-1525607551316-4a8e16d1f9ba?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 2400,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 2400,
    maxMoisturePercent: 20.0,
    season: "Summer & Kharif",
    unit: "quintal",
    description: "Tender, green ridged fresh okra pods for early morning mandi arrivals.",
  },
  {
    id: "spinach",
    cropName: "Spinach (Palak)",
    commonName: "Spinach / Greens (Palakura)",
    variety: "All Green / Pusa Jyoti",
    category: "Vegetables",
    imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 1650,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 1650,
    maxMoisturePercent: 25.0,
    season: "All-Season 2025-26",
    unit: "quintal",
    description: "Tender dark green leafy vegetable bundles for urban farmer markets.",
  },

  // ==========================================
  // 6. FRUITS
  // ==========================================
  {
    id: "mango",
    cropName: "Mango",
    commonName: "King of Fruits (Aam / Mamidi)",
    variety: "Banganapalli / Alphonso / Totapuri",
    category: "Fruits",
    imageUrl: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 4800,
    govtBonusPerQuintal: 200,
    effectiveRatePerQuintal: 5000,
    maxMoisturePercent: 20.0,
    season: "Summer 2026",
    unit: "quintal",
    description: "GI-tagged sweet Banganapalli mangoes for AP horticulture procurement.",
  },
  {
    id: "banana",
    cropName: "Banana",
    commonName: "Banana (Kela / Arati)",
    variety: "Grand Naine (G9) / Robusta",
    category: "Fruits",
    imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 2200,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 2200,
    maxMoisturePercent: 20.0,
    season: "All-Season 2025-26",
    unit: "quintal",
    description: "High-yield commercial tissue culture fresh green fruit bunches.",
  },
  {
    id: "orange",
    cropName: "Orange",
    commonName: "Nagpur Orange / Mandarin",
    variety: "Nagpur Mandarin / Coorg",
    category: "Fruits",
    imageUrl: "https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 3400,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 3400,
    maxMoisturePercent: 18.0,
    season: "Winter 2025-26",
    unit: "quintal",
    description: "Juicy citrus oranges with vibrant peel and high vitamin C.",
  },
  {
    id: "sweet-orange",
    cropName: "Sweet Orange (Mosambi / Battayi)",
    commonName: "Sweet Lime / Mosambi",
    variety: "Sathgudi / Mosambi",
    category: "Fruits",
    imageUrl: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 3600,
    govtBonusPerQuintal: 100,
    effectiveRatePerQuintal: 3700,
    maxMoisturePercent: 18.0,
    season: "Kharif & Rabi",
    unit: "quintal",
    description: "Famous AP Sathgudi sweet lime for regional wholesale procurement.",
  },
  {
    id: "apple",
    cropName: "Apple",
    commonName: "Apple (Seb)",
    variety: "Royal Delicious / Red Gold",
    category: "Fruits",
    imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 6800,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 6800,
    maxMoisturePercent: 15.0,
    season: "Autumn 2025-26",
    unit: "quintal",
    description: "Premium graded crisp red apples from high-altitude orchards.",
  },
  {
    id: "grapes",
    cropName: "Grapes",
    commonName: "Table Grapes (Angoor)",
    variety: "Thompson Seedless / Sharad Seedless",
    category: "Fruits",
    imageUrl: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 5200,
    govtBonusPerQuintal: 150,
    effectiveRatePerQuintal: 5350,
    maxMoisturePercent: 18.0,
    season: "Winter/Spring 2026",
    unit: "quintal",
    description: "Export and domestic market sweet seedless table grape bunches.",
  },
  {
    id: "guava",
    cropName: "Guava",
    commonName: "Guava (Amrood / Jaama)",
    variety: "Allahabad Safeda / L-49 (Lucknow)",
    category: "Fruits",
    imageUrl: "https://images.unsplash.com/photo-1536511135898-356f91666ff7?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 2500,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 2500,
    maxMoisturePercent: 18.0,
    season: "Rabi & Summer",
    unit: "quintal",
    description: "Rich pulp round white-flesh guavas for mandi auctions.",
  },
  {
    id: "papaya",
    cropName: "Papaya",
    commonName: "Papaya (Papita / Boppayi)",
    variety: "Red Lady 786 / Taiwan Hybrid",
    category: "Fruits",
    imageUrl: "https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 1900,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 1900,
    maxMoisturePercent: 20.0,
    season: "All-Season 2025-26",
    unit: "quintal",
    description: "Large, firm sweet red-fleshed papayas for commercial packing.",
  },
  {
    id: "pomegranate",
    cropName: "Pomegranate",
    commonName: "Pomegranate (Anaar / Danimma)",
    variety: "Bhagwa / Ruby",
    category: "Fruits",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 8500,
    govtBonusPerQuintal: 250,
    effectiveRatePerQuintal: 8750,
    maxMoisturePercent: 15.0,
    season: "Annual 2025-26",
    unit: "quintal",
    description: "Glossy deep-red Bhagwa arils with high market and export demand.",
  },
  {
    id: "watermelon",
    cropName: "Watermelon",
    commonName: "Watermelon (Tarbooz / Pulla)",
    variety: "Sugar Baby / Kiran Hybrid",
    category: "Fruits",
    imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80",
    mspPerQuintal: 1350,
    govtBonusPerQuintal: 0,
    effectiveRatePerQuintal: 1350,
    maxMoisturePercent: 20.0,
    season: "Summer 2026",
    unit: "quintal",
    description: "Crisp, deeply red flesh sweet fruit for seasonal mass mandi procurement.",
  },
];

/**
 * Filter crops by category and/or query string (case-insensitive)
 */
export function filterCrops(
  crops: CropItem[],
  category: string,
  searchQuery: string
): CropItem[] {
  const q = searchQuery.trim().toLowerCase();
  return crops.filter(crop => {
    const matchesCat =
      category === "ALL" ||
      crop.category.toLowerCase() === category.toLowerCase();

    if (!matchesCat) return false;
    if (!q) return true;

    return (
      crop.cropName.toLowerCase().includes(q) ||
      crop.commonName.toLowerCase().includes(q) ||
      crop.variety.toLowerCase().includes(q) ||
      crop.category.toLowerCase().includes(q) ||
      crop.description.toLowerCase().includes(q)
    );
  });
}

/**
 * Fast crop image lookup that checks the catalogue first, then falls back safely.
 */
export function getCatalogueCropImage(cropName: string): string {
  if (!cropName) return "https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=800&q=80";
  const direct = CROP_CATALOGUE.find(
    c => c.cropName.toLowerCase() === cropName.toLowerCase() ||
         c.commonName.toLowerCase().includes(cropName.toLowerCase()) ||
         cropName.toLowerCase().includes(c.cropName.toLowerCase())
  );
  if (direct) return direct.imageUrl;
  return "https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=800&q=80";
}
